kind: pipeline
type: docker
name: default

steps:
- name: deploy_staging
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: host
    username: root
    port: 22
    key:
      from_secret: ssh_key
    script:
      
      - docker run -d --restart=always -p 3001:3001 -v /root/uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1
  when:
    event:
    - push
    branch:
    - main